### ISSUE TITLE
Failed assertion: line 158 pos 14: 'stateKey != null': is not true

### ISSUE THREAD

**Issue by PhantomRay** [famedly/matrix-dart-sdk#1840]
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [ ] I already asked for help in the chat

### In which Project did the bug appear?

Other

### On which platform did the bug appear?

Android, iOS

### SDK Version

0.29.7~0.29.9

### Describe the problem caused by this bug

1. go to a room, redact a message
2. restart app
3. go to the room again, getTimeline throw an error

```
\^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ 'package:matrix/src/room.dart': Failed assertion: line 158 pos 14: 'stateKey != null': is not true.<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ #0   _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)<…>
flutter: \^[[38;5;196m│ #1   _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)<…>
flutter: \^[[38;5;196m│ #2   Room.setState (package:matrix/src/room.dart:158:14)<…>
flutter: \^[[38;5;196m│ #3   Room.postLoad (package:matrix/src/room.dart:120:9)<…>
flutter: \^[[38;5;196m│ #4   <asynchronous suspension><…>
flutter: \^[[38;5;196m│ #5   Room.getTimeline (package:matrix/src/room.dart:1445:5)<…>
flutter: \^[[38;5;196m│ #6   <asynchronous suspension><…>
flutter: \^[[38;5;196m│ #7   ChatPageController._initTimeline (package:my_app/modules/im/chat/controller.dart:306:19)<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ ⛔ _throwNew<…>
```

### Screenshots or Logs

The following redact event's stateKey is null, which throws the exception

![WechatIMG28541](https://github.com/famedly/matrix-dart-sdk/assets/2357322/87038320-bb84-4c42-b12b-2d80629bdb26)

**Comment by td-famedly** [comment]
fixed in https://github.com/famedly/matrix-dart-sdk/pull/1835

**Comment by PhantomRay** [comment]
This is not fixed. Linking new PR https://github.com/famedly/matrix-dart-sdk/pull/1848
